<?php
function uc_fill_tags_actions_action_info() {
	return array(
		'uc_fill_tags_action_fill_tags' => array(
		'type' => 'node',
		'label' => t('Modify/fill product tags field'),
		'configurable' => FALSE,
		'triggers' => array(
			'nodeapi' => array('update'),
			),
		),
	);
}

function uc_fill_tags_action_fill_tags($node, $context = array()) {
	node_load($node);
	if (isset($node->field_category['und'])) {
		$tags = _ucfta_get_search_tags($node->field_category['und']);
	}
	if (isset($node->field_search_tags)) {
		$tags .= '.' . str_replace('-', ' ', _tlr($node->title));

		$node->field_search_tags['und'][0]['value'] = $tags;
		$node->field_search_tags['und'][0]['safe_value'] = $tags;
	}
	node_save($node);
}

function _ucfta_get_search_tags($field_category) {
	$output = '';
	$str = array();
	$tname = '';
	foreach ($field_category as $category) {
		$tname = _ucfta_get_term($category['tid']);
		$str[] = $tname;
	}
	if (!empty($str)) {
		$output = implode($str, '.');
	}
	$output .= '.' . str_replace('-', ' ', _tlr($output));
	return $output;
}

function _ucfta_get_term($tid) {
	if ($tid !== '_none') {
		return db_select('taxonomy_term_data', 't')
		->fields('t', array('name'))
		->condition('tid', $tid)
		->execute()
		->fetchField();
	}
	return FALSE;
}
