<?php
function uc_order_export_action_info() {
  return array(
  'uc_order_export_action_export_xml' => array(
								'label' => t('Export to All Parcels XML'),
								'type' => 'uc_order',
								'aggregate' => TRUE,
								'configurable' => FALSE,
								'triggers' => array('any'),
								),
							);
}

function uc_order_export_action_export_xml($orders, $context = array()) {
	$output = '<shipments version="1">' . "\n";
	foreach ($orders as $order) {
		$courier_identifier = '';
		$terminal_id = '';
		$terminal = explode("\n", $order->flatrate_terminal);
		if (isset($terminal[1]) && $terminal[1]) {
			$courier_identifier = $terminal[1];
		}
		if (isset($terminal[0]) && $terminal[0]) {
			$terminal_id = $terminal[0];
		}
		$total_weight = _uc_order_export_action_get_order_weight($order);
		$output .= '<shipment>' . "\n";
		$output .= '<reference>' . $order->order_id . '</reference>' . "\n";
		$output .= '<weight>' . $total_weight . '</weight>' . "\n";
		$output .= '<remark></remark>' . "\n";
		$output .= '<additional_information></additional_information>' . "\n";
		$output .= '<number_of_parcels>1</number_of_parcels>' . "\n";
		$output .= '<courier_identifier>' . $courier_identifier . '</courier_identifier>' . "\n";
		$output .= '<box_size>S</box_size>' . "\n";
		$output .= '<receiver>' . "\n";
		$output .= '<name>' . $order->delivery_first_name . ' ' . $order->delivery_last_name . '</name>' . "\n";
		$output .= '<street>' . $order->delivery_street1 . ' ' . $order->delivery_street2 . '</street>' . "\n";
		$output .= '<postal_code>' . $order->delivery_postal_code .  '</postal_code>' . "\n";
		$output .= '<city>' . $order->delivery_city . '</city>' . "\n";
		$output .= '<phone>' . $order->delivery_phone . '</phone>' . "\n";
		$output .= '<email>' . $order->primary_email . '</email>' . "\n";
		$output .= '<parcel_terminal_identifier>' . $terminal_id . '</parcel_terminal_identifier>' . "\n";
		$output .= '<country_code>LT</country_code>' . "\n";
		$output .= '</receiver>' . "\n";
		$output .= '<services>' . "\n";
		$output .= '<express_delivery>false</express_delivery>' . "\n";
		$output .= '<inform_sender_email>false</inform_sender_email>' . "\n";
		$output .= '</services>' . "\n";
		$output .= '</shipment>' . "\n";
	}
	$output .= '</shipments>';
	$filename = 'all_parcels-' . date('Y-m-d-H-i-s') . '.xml';
	header('Content-Type: application/xml; charset=UTF-16');
    header('Content-Disposition: attachement; filename="' . $filename. '"');
	$f = fopen('php://output', 'w');
	fputs($f, "\xEF\xBB\xBF");
	echo $output;
	fclose($f);
	exit;
}

function _uc_order_export_action_get_order_weight($order) {
	$total_weight = 0;
	foreach ($order -> products as $product) {
		$product_weight = $product->weight;
		if ($product->weight_units == 'g') {
			$product_weight = $product_weight / 1000;
		}
		$total_weight += $product_weight;
	}
	return $total_weight;
}
